apiVersion: v1
kind: Service
metadata:
  name: cam-server-service
  annotations:
   # the ARN for your site cert from amazon certificate manager
   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: TODO 
   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
  - port: 443 # the port that this service should serve on
    # the container on each pod to connect to, can be a name
    # (e.g. 'www') or a number (e.g. 80)
    targetPort: 8080
    protocol: TCP
  # just like the selector in the deployment,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    app: cam-server
